image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-browser
  - port: 3035
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 6379
    onOpen: ignore

tasks:
  - name: Rails server
    before: |
      redis-server &
    init: >
      gem install foreman solargraph &&
      bin/setup
    command: >
      if [ -f package.json ] then [ yarn install && bin/dev ] || bin/dev
  - command: >
      printf "To open preview (cmd+) click here:  $(gp url 3000)\n"